version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://kido_user:kido_password@db:5432/kido_db
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kido_user
      - POSTGRES_PASSWORD=kido_password
      - POSTGRES_DB=kido_db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
